name: Build docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        run: python -m pip install --upgrade pip && pip install -e .
      - name: Install docs requirements
        run: pip install -r docs/requirements.txt
      - name: Build docs
        run: cd docs && make html && cd ..
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
