name: Build Runhouse Image

on:
  push:
    branches:
      - stable
  workflow_dispatch:
    inputs:
      version:
        description: 'Runhouse version (leave empty for "latest")'
        required: false

jobs:
  build-and-push:
    name: Create new image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image tag
        id: get_version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION="latest"
          fi
          echo "Using version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # Build image based on specified pypi version
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/base/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/runhouse:${{ env.VERSION }}
          build-args: |
            INSTALL_METHOD=pypi
            RUNHOUSE_VERSION=${{ env.VERSION }}
