name: Generate Docs for Tag

on:
  push:
    tags:
      - '*'  # Triggers on any tag push
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag Name (ex: v0.0.32)'
        required: false # Allow empty for cases where the release event provides the tag
        default: ''

jobs:
  build-docs-for-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        pip install runhouse sshtunnel python-dotenv gitpython

    - name: Determine Tag Name
      id: determine-tag
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "Tag name from release: ${{ github.event.release.tag_name }}"
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        elif [[ -n "${{ github.event.inputs.tag-name }}" ]]; then
          echo "Tag name from manual input: ${{ github.event.inputs.tag-name }}"
          echo "tag_name=${{ github.event.inputs.tag-name }}" >> $GITHUB_ENV
        else
          echo "Error: No tag name provided"
          exit 1
        fi
      shell: bash

    - name: Run docs build script for specific tag
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TAG_NAME: ${{ env.tag_name }}
      run: |
        python scripts/generating_docs.py --tag-name "${{ env.TAG_NAME }}"
