name: Run pre-commit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pre-commit
        run: python -m pip install --upgrade pip && pip install pre-commit
      - name: Lint code
        run: pre-commit run --all-files
      - name: Show diff
        run: git --no-pager diff --color=always
